# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 66e84ff6463470f047447bf6cecd77039942ca068075c5acd8e0305778d5736f45a4640d307fd14da5b6f56f0bdc4d62e5061bc131cec5e957ed624be81077a6

test:
  secret_key_base: 0813a996ece921a0fda83f078b29f27afd3aca48c438535a51478cf67dca81dde6cea49fe9083b495e5c86feb005e1ae81eccab13c6f5f33b8e34889a41e6f18

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
